apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    service: {{ .Values.DeployLables.lable2 }}
  #type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.conteiner.port }}
      protocol: TCP

